steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/aamundaray/check:2.1.0', '.']
  secretEnv: ['CHECK_MONGO_ROOT_USERNAME', 'CHECK_MONGO_ROOT_PASSWORD','CHECK_MONGO_USER','CHECK_MONGO_PASSWORD','CHECK_JWT_SECRET']
- name: 'docker/compose:1.29.2'
  args: ['up', '-d']
  env:
    - 'TZ=$$_TZ'
    - 'CHECK_ENV=$$_CHECK_ENV'
    - 'CHECK_PORT=$$_CHECK_PORT'
    - 'CHECK_LOG_PATH=$$_CHECK_LOG_PATH'
    - 'CHECK_MONGO_DOMAIN=$$_CHECK_MONGO_DOMAIN'
    - 'CHECK_MONGO_PORT=$$_CHECK_MONGO_PORT'
    - 'CHECK_MONGO_DATABASE=$$_CHECK_MONGO_DATABASE'
    - 'CHECK_MONGO_USER=$$CHECK_MONGO_USER'
    - 'CHECK_MONGO_PASSWORD=$$CHECK_MONGO_PASSWORD'
    - 'CHECK_JWT_SECRET=$$CHECK_JWT_SECRET'
    - 'CHECK_MONGO_ROOT_USERNAME=$$CHECK_MONGO_ROOT_USERNAME'
    - 'CHECK_MONGO_ROOT_PASSWORD=$$CHECK_MONGO_ROOT_PASSWORD'
  secretEnv: ['CHECK_MONGO_ROOT_USERNAME', 'CHECK_MONGO_ROOT_PASSWORD','CHECK_MONGO_USER','CHECK_MONGO_PASSWORD','CHECK_JWT_SECRET']
images: ['gcr.io/$PROJECT_ID/aamundaray/check-server:2.1.0']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/CHECK_MONGO_ROOT_USERNAME/versions/1
    env: 'CHECK_MONGO_ROOT_USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/CHECK_MONGO_ROOT_PASSWORD/versions/1
    env: 'CHECK_MONGO_ROOT_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/CHECK_MONGO_USER/versions/1
    env: 'CHECK_MONGO_USER'
  - versionName: projects/$PROJECT_ID/secrets/CHECK_MONGO_PASSWORD/versions/1
    env: 'CHECK_MONGO_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/CHECK_JWT_SECRET/versions/1
    env: 'CHECK_JWT_SECRET'