version: '3.9'
services:
  check:
    image: aamundaray/check:2.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: check
    restart: always
    environment:
      - TZ=${TZ}
      - CHECK_MONGO_DOMAIN=${CHECK_MONGO_DOMAIN}
      - CHECK_MONGO_PORT=${CHECK_MONGO_PORT}
      - CHECK_MONGO_DATABASE=${CHECK_MONGO_DATABASE}
      - CHECK_MONGO_USER=${CHECK_MONGO_USER}
      - CHECK_MONGO_PASSWORD=${CHECK_MONGO_PASSWORD}
      - CHECK_JWT_SECRET=${CHECK_JWT_SECRET}
    privileged: true
    env_file: .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.3
    container_name: mongodb
    restart: always
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_DATABASE=${CHECK_MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    env_file: .env
    volumes:
      - mongodb:/data/db
      - ./src/config/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  check-proxy:
    image: aamundaray/check-proxy:1.0.0
    container_name: check-proxy
    restart: always
    build:
      context: ./check-proxy
      dockerfile: Dockerfile
      args:
        CHECK_PORT: ${CHECK_PORT}
    env_file: .env
    ports:
      - 443:443
    depends_on:
      - check
volumes:
  mongodb: {}