version: '3.9'
services:
  check:
    image: aamundaray/check:2.2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: check
    restart: always
    environment:
      - TZ=${TZ}
      - CHECK_MONGO_DOMAIN=${CHECK_MONGO_DOMAIN}
      - CHECK_MONGO_DATABASE=${CHECK_MONGO_DATABASE}
      - CHECK_MONGO_USER=${CHECK_MONGO_USER}
      - CHECK_MONGO_PASSWORD=${CHECK_MONGO_PASSWORD}
      - CHECK_JWT_SECRET=${CHECK_JWT_SECRET}
    privileged: true
    env_file: .env
volumes:
  mongodb: {}